<?php 
	include_once 'adminHeader.php';
	include_once './_includes/config.php';

	$monsterQuery = "SELECT * FROM monsterList;";
	$data = selectMonsters($monsterQuery);
?>
<h1 class="pageTitle">Monster Gallery</h1>

<!-- Gumamit ng looping para idisplay lahat ng monsters na nasa database -->
<!-- Ilagay sa loob ng _images/monsters -->

<?php print_r($data); ?>
<!-- Sample -->
<div class="container">
	
		<div class="col-xl-4 col-md-6">
			<div class="card monsterContainer">
			  <?php echo '<img class="card-img-top monster-img" src="data:image/jpeg;base64,'.base64_encode( $monsterInfo['monster_image'] ).'"/>'; ?>
			  	<div class="card-body">
				    <h2 class="card-title">Vaccine Man</h2>
				    <p class="card-text">Vaccine Man (ワクチンマン, Wakuchin Man) was a Mysterious Being supposedly born from the release of excessive pollution and waste generated by the industries made by human beings</p>
				    <hr>
				    <a href="#">READ MORE</a>
			  	</div>
			</div>
		</div>
	</div>
</div>

</body>
</html>